### PR TITLE
[ACR-8] Uses secrets in the steps

### PR DESCRIPTION
**Pull request by josearmandojacq**
As part of the setup it recommended to store the AZURE_OPENAI_API_KEY in the secrets. In the README the variable is accessed using vars

### CODE REVIEW

**Comment by vivianintech** [comment]
great catch @josearmandojacq!

**Review by vivianintech — APPROVED** [review]

**Comment by sanglt** [comment]
@vivianintech @josearmandojacq actually the secret should use as an env for the action. Our README and jobs implemented use the env value from secret.

> To make a secret available to an action, you must set the secret as an input or environment variable in the workflow file. Review the action's README file to learn about which inputs and environment variables the action expects.

https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions#accessing-your-secrets

**Comment by vivianintech** [comment]
ahh that's true!! Awesome, thanks a @sanglt for catching this 🙏
I'll revert this change

**Comment by josearmandojacq** [comment]
@sanglt to see if I understood. After declaring it as a secret, you can access it from envs.
🤔
I did like in my PR and it works 🤷🏽‍♂️

**Comment by josearmandojacq** [comment]
@vivianintech @sanglt That is interesting. I created a project secret and this is why my change works. It is intended to store it differently?

**Pull request merged**
